import { useEffect, useState } from 'react'
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import { resourceApi } from '../services/api'

const kinds = [['notes', 'Notes'], ['previous_paper', 'Previous Year Papers'], ['syllabus', 'Syllabus'], ['study_material', 'Study Material'], ['useful_link', 'Useful Links']]
function ResourceShare() {
  const { user, token, loading: authLoading } = useAuth(); const [params] = useSearchParams(); const id = params.get('id'); const navigate = useNavigate()
  const [form, setForm] = useState({ title: '', description: '', type: 'notes', subject: '', course: '', semester: '', year: '', externalUrl: '' }); const [file, setFile] = useState(null); const [hasExisting, setHasExisting] = useState(false); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!id || !token) return; let live = true; resourceApi.get(id, token).then(({ resource }) => { if (!live) return; if (!resource.isMine) { setError('Only your own resources can be edited.'); return } setForm({ title: resource.title, description: resource.description || '', type: resource.type, subject: resource.subject || '', course: resource.course || '', semester: resource.semester || '', year: resource.year || '', externalUrl: resource.externalUrl || '' }); setHasExisting(Boolean(resource.fileUrl)) }).catch(() => live && setError('Unable to load resource. Please try again.')).finally(() => live && setLoading(false)); return () => { live = false } }, [id, token])
  if (authLoading) return <section className="placeholder">Loading your account...</section>
  if (!user || !token) return <Navigate to="/login" replace state={{ from: id ? `/resources/share?id=${id}` : '/resources/share' }} />
  const set = (key, value) => { setForm((state) => ({ ...state, [key]: value })); setError('') }
  const submit = async (event) => { event.preventDefault(); setError(''); if (form.type === 'useful_link' && (file || (!form.externalUrl && !hasExisting))) return setError('Add a valid HTTPS link for a Useful Link.'); if (form.type !== 'useful_link' && !file && !form.externalUrl && !hasExisting) return setError('Choose a file or enter an HTTPS external link.'); if (form.externalUrl && !/^https:\/\//i.test(form.externalUrl)) return setError('Resource links must use HTTPS.'); if (file && file.size > 10 * 1024 * 1024) return setError('File must be 10MB or smaller.'); if (file && !['application/pdf', 'text/plain', 'image/jpeg', 'image/png'].includes(file.type)) return setError('Choose a PDF, TXT, JPG, or PNG file.'); setSaving(true); try { const payload = { ...form, externalUrl: form.type === 'useful_link' || form.externalUrl ? form.externalUrl : '' }; const result = id ? await resourceApi.update(token, id, payload, file) : await resourceApi.create(token, payload, file); navigate(`/resources/${result.resource._id}`, { replace: true }) } catch { setError(id ? 'Something went wrong. Please try again.' : 'Unable to upload resource. Please try again.') } finally { setSaving(false) } }
  return <section className="resource-form-page"><Link className="text-link" to="/resources">← Back to resources</Link><div className="resources-heading"><div><p className="eyebrow">Help your classmates learn</p><h1>{id ? 'Edit Resource' : 'Share Resource'}</h1></div></div>{loading ? <div className="empty-state">Loading resource...</div> : <form className="form-stack resource-form" onSubmit={submit}><label>Title<input required maxLength={200} value={form.title} onChange={(e) => set('title', e.target.value)} /></label><label>Description<textarea maxLength={2000} rows={5} value={form.description} onChange={(e) => set('description', e.target.value)} /></label><label>Type<select value={form.type} onChange={(e) => set('type', e.target.value)}>{kinds.map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select></label><div className="resource-form-grid"><label>Subject<input maxLength={150} value={form.subject} onChange={(e) => set('subject', e.target.value)} /></label><label>Course<input maxLength={150} value={form.course} onChange={(e) => set('course', e.target.value)} /></label><label>Semester<input maxLength={50} value={form.semester} onChange={(e) => set('semester', e.target.value)} /></label><label>Year<input type="number" min="1900" max="2100" value={form.year} onChange={(e) => set('year', e.target.value)} /></label></div>{form.type !== 'useful_link' && <label>File (PDF, TXT, JPG, PNG; max 10MB)<input type="file" accept=".pdf,.txt,.jpg,.jpeg,.png,application/pdf,text/plain,image/jpeg,image/png" onChange={(e) => { setFile(e.target.files?.[0] || null); setError('') }} />{file ? <small>Selected: {file.name}</small> : hasExisting && <small>Existing file attached. Choose another file to replace it.</small>}</label>}<label>External HTTPS link{form.type === 'useful_link' && ' (required)'}<input type="url" placeholder="https://..." value={form.externalUrl} onChange={(e) => set('externalUrl', e.target.value)} /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button" disabled={saving || loading}>{saving ? 'Uploading...' : id ? 'Save changes' : 'Share Resource'}</button></form>}</section>
}
export default ResourceShare
