import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { resourceApi } from '../services/api'

const types = [['', 'All types'], ['notes', 'Notes'], ['previous_paper', 'Previous Year Papers'], ['syllabus', 'Syllabus'], ['study_material', 'Study Material'], ['useful_link', 'Useful Links']]
const label = (type) => types.find(([value]) => value === type)?.[1] || type

function Resources() {
  const [filters, setFilters] = useState({ search: '', type: '', subject: '', course: '', semester: '', year: '' })
  const [items, setItems] = useState([]); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(false)
  useEffect(() => { let live = true; const timer = setTimeout(() => { setLoading(true); setError(false); resourceApi.list({ ...filters, page, limit: 12 }).then((data) => { if (live) { setItems(data.resources || []); setPages(data.pagination?.pages || 1) } }).catch(() => live && setError(true)).finally(() => live && setLoading(false)) }, 200); return () => { live = false; clearTimeout(timer) } }, [filters, page])
  const set = (key, value) => { setPage(1); setFilters((state) => ({ ...state, [key]: value })) }
  return <section className="resources-page"><div className="resources-heading"><div><p className="eyebrow">Shared by your campus</p><h1>Campus Resources</h1><p>Find notes, papers, syllabi and study material shared by students.</p></div><div className="resource-page-actions"><Link className="secondary-button" to="/resources/my-resources">My Resources</Link><Link className="primary-button" to="/resources/share">Share Resource</Link></div></div>
    <div className="resource-filters"><input aria-label="Search resources" type="search" placeholder="Search resources..." value={filters.search} onChange={(e) => set('search', e.target.value)} /><select aria-label="Type" value={filters.type} onChange={(e) => set('type', e.target.value)}>{types.map(([v, n]) => <option key={v} value={v}>{n}</option>)}</select><input placeholder="Subject" value={filters.subject} onChange={(e) => set('subject', e.target.value)} /><input placeholder="Course" value={filters.course} onChange={(e) => set('course', e.target.value)} /><input placeholder="Semester" value={filters.semester} onChange={(e) => set('semester', e.target.value)} /><input placeholder="Year" type="number" value={filters.year} onChange={(e) => set('year', e.target.value)} /></div>
    {error && <p className="form-error" role="alert">Something went wrong. Please try again.</p>}{loading ? <div className="empty-state">Loading resources...</div> : !items.length ? <div className="empty-state">{filters.search || filters.type || filters.subject || filters.course || filters.semester || filters.year ? 'No resources match your search.' : 'No resources found.'}</div> : <div className="resource-grid">{items.map((item) => <article className="resource-card" key={item._id}><span className="resource-type">{label(item.type)}</span><h2><Link to={`/resources/${item._id}`}>{item.title}</Link></h2><p>{[item.subject, item.course, item.semester && `Semester ${item.semester}`, item.year].filter(Boolean).join(' · ')}</p><p className="resource-description">{item.description || 'No description provided.'}</p><div className="resource-card-footer"><time>{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(item.createdAt))}</time><Link className="secondary-button" to={`/resources/${item._id}`}>{item.type === 'useful_link' ? 'View Resource' : 'View / Download'}</Link></div></article>)}</div>}
    {pages > 1 && <div className="voice-pagination"><button className="secondary-button" disabled={page <= 1} onClick={() => setPage((n) => n - 1)}>Previous</button><span>Page {page} of {pages}</span><button className="secondary-button" disabled={page >= pages} onClick={() => setPage((n) => n + 1)}>Next</button></div>}
  </section>
}
export default Resources
