import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../context/useAuth'
import { resourceApi } from '../services/api'

const names = { notes: 'Notes', previous_paper: 'Previous Year Papers', syllabus: 'Syllabus', study_material: 'Study Material', useful_link: 'Useful Links' }
function ResourceDetails() {
  const { id } = useParams(); const { token, user } = useAuth(); const navigate = useNavigate(); const [resource, setResource] = useState(null); const [error, setError] = useState(false); const [busy, setBusy] = useState(false); const [reporting, setReporting] = useState(false); const [reason, setReason] = useState('spam'); const [message, setMessage] = useState('')
  useEffect(() => { let live = true; resourceApi.get(id, token).then((data) => live && setResource(data.resource)).catch(() => live && setError(true)); return () => { live = false } }, [id, token])
  const open = async () => { if (!token) return navigate('/login', { state: { from: `/resources/${id}` } }); setBusy(true); try { const result = await resourceApi.download(token, id); window.location.assign(result.url) } catch { setError(true) } finally { setBusy(false) } }
  const submitReport = async (event) => { event.preventDefault(); if (!token) return navigate('/login'); setBusy(true); try { await resourceApi.report(token, id, { reason, description: message }); setReporting(false); setMessage('') } catch { setError(true) } finally { setBusy(false) } }
  if (error && !resource) return <section className="empty-state">Something went wrong. Please try again.</section>
  if (!resource) return <section className="empty-state">Loading resource...</section>
  return <section className="resource-detail-page"><Link className="text-link" to="/resources">← Back to resources</Link><article className="resource-detail"><span className="resource-type">{names[resource.type]}</span><h1>{resource.title}</h1><p className="resource-detail-meta">{[resource.subject, resource.course, resource.semester && `Semester ${resource.semester}`, resource.year].filter(Boolean).join(' · ')}</p><p className="resource-detail-description">{resource.description || 'No description provided.'}</p><p>Shared {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(resource.createdAt))} · {resource.downloads || 0} downloads</p>{resource.status !== 'active' && <p className="resource-status">{resource.status}</p>}<div className="resource-page-actions">{resource.status === 'active' && <button className="primary-button" type="button" onClick={open} disabled={busy}>{busy ? 'Opening...' : resource.type === 'useful_link' ? 'Open Resource' : 'View / Download'}</button>}{resource.isMine && <Link className="secondary-button" to={`/resources/share?id=${resource._id}`}>Edit</Link>}{user && !resource.isMine && resource.status === 'active' && <button className="secondary-button" onClick={() => setReporting((value) => !value)}>Report Resource</button>}</div>{reporting && <form className="resource-report-form" onSubmit={submitReport}><label>Reason<select value={reason} onChange={(e) => setReason(e.target.value)}>{[['spam','Spam'],['copyright_concern','Copyright concern'],['inappropriate_content','Inappropriate content'],['incorrect_resource','Incorrect resource'],['malicious_link','Malicious link'],['other','Other']].map(([v,n]) => <option key={v} value={v}>{n}</option>)}</select></label><label>Details<textarea value={message} maxLength={1000} onChange={(e) => setMessage(e.target.value)} /></label><button className="primary-button" disabled={busy}>Submit report</button></form>}{error && <p className="form-error" role="alert">Something went wrong. Please try again.</p>}</article></section>
}
export default ResourceDetails
