import { useEffect, useState } from 'react'
import { engagementApi } from '../services/api'

const localDateTime = (date) => { const value = new Date(date.getTime() - date.getTimezoneOffset() * 60000); return value.toISOString().slice(0, 16) }

function SellerOfferManager({ product, token }) {
  const [offers, setOffers] = useState([]); const [offerPrice, setOfferPrice] = useState(''); const [startTime, setStartTime] = useState(localDateTime(new Date())); const [endTime, setEndTime] = useState(localDateTime(new Date(Date.now() + 86400000))); const [editing, setEditing] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const refresh = () => engagementApi.myOffers(token).then((data) => setOffers((data.offers || []).filter((offer) => offer.product?._id === product._id)))
  useEffect(() => { refresh().catch((requestError) => setError(requestError.message)) }, [product._id, token])
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const payload = { offerPrice: Number(offerPrice), startTime: new Date(startTime).toISOString(), endTime: new Date(endTime).toISOString() }; if (editing) await engagementApi.updateOffer(token, editing, payload); else await engagementApi.createOffer(token, { product: product._id, ...payload }); setEditing(''); setOfferPrice(''); await refresh() } catch (requestError) { setError(requestError.message) } finally { setBusy(false) } }
  return <section className="seller-offer-manager"><h3>Seller Offers</h3><p>Offers do not change your listed product price.</p><form className="resource-form-grid" onSubmit={submit}><label>Offer price<input required type="number" min="1" max={Math.max(1, product.price - 1)} value={offerPrice} onChange={(event) => setOfferPrice(event.target.value)} /></label><label>Starts<input required type="datetime-local" value={startTime} onChange={(event) => setStartTime(event.target.value)} /></label><label>Ends<input required type="datetime-local" value={endTime} onChange={(event) => setEndTime(event.target.value)} /></label><button className="primary-button" disabled={busy}>{busy ? 'Saving...' : editing ? 'Update Offer' : 'Create Offer'}</button></form>{error && <p className="form-error" role="alert">{error}</p>}{offers.map((offer) => <article className="exchange-request-card" key={offer._id}><strong>{offer.effectiveStatus}: ₹{offer.offerPrice}</strong><span>Ends {new Date(offer.endTime).toLocaleString()}</span>{!['expired', 'cancelled'].includes(offer.effectiveStatus) && <div><button className="secondary-button" type="button" onClick={() => { setEditing(offer._id); setOfferPrice(String(offer.offerPrice)); setStartTime(localDateTime(new Date(offer.startTime))); setEndTime(localDateTime(new Date(offer.endTime))) }}>Edit</button><button className="secondary-button" type="button" onClick={async () => { try { await engagementApi.cancelOffer(token, offer._id); await refresh() } catch (requestError) { setError(requestError.message) } }}>Cancel</button></div>}</article>)}</section>
}

export default SellerOfferManager
